### ISSUE TITLE
Geo location for phone country code not working on old AuthUI

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4295] opened 2024-06-11 13:08 UTC
On staging, the first country code in the list is always selected by default (Afghanistan) instead of the user's location determined by IP as expected.

This only affects the old AuthUI, AuthUI v2 is not affected

**Comment by tung2744** [comment] 2024-06-12 10:57
It looks like a bug of the intl-tel-input package. I've verified the options we passed to initialize the input is correct. However the initial option is not selected correctly.

**Comment by fungc-io** [comment] 2024-06-12 11:44
does the newer version of intl-tel-input allow selecting the country based on location via other means?

**Comment by tung2744** [comment] 2024-06-12 12:18
The fix is in this pr:
https://github.com/authgear/authgear-server/pull/4301

The problem is the behavior of the input changed, from case insensitive to case sensitive.

**Comment by fungc-io** [comment] 2024-06-12 12:40
thanks!

**Closed** 2024-06-13 09:43 UTC
