### ISSUE TITLE
Update webhook events

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-server#1041] opened 2021-03-09 04:52 UTC
1. Include user preferred language in webhook context for developer to customise message (title and reason)
1. Update webhook response to add title and drop data. e.g. 
        ```
        {
        "is_allowed": false,
        "title": "Signup is not allowed",
        "reason": "Any resaon"
        }
        ```
1. If reason is not provided in hook, error page will show the default reason with basic context. e.g. "Signup is blocked by webhook".
1. Rename / drop some existing webhooks
     - Rename "before_user_create, after_user_create" to "before_signup_completion, after_signup_completion"
     - (TBC)

**Comment by carmenlau** [comment] 2021-03-11 08:41
@louischan-oursky @chpapa @mr9dollars 

Here is a summary for us to review the webhooks,

The webhooks that are using by some existing projects:

- after_identity_create
- after_identity_delete
- after_user_promote
- after_user_create

The webhooks that we implemented in code:

- before_user_create / after_user_create
- before_identity_create / after_identity_create
- before_identity_delete / after_identity_delete
- before_identity_update / after_identity_update
- before_session_create / after_session_create
- before_session_delete / after_session_delete
- before_user_promote / after_user_promote
- user_sync

My thought:

1. In product meeting, Ben mentioned that wants to change `(before|after)_user_create` to `(before|after)_signup_completion`, but after checking, I found that the hook will be called in all user creation cases (signup by user / create user by admin). Seems `user_create` is more accurate.

1. After reading the detail, I think the current hooks definition are quite well actually. Instead of separating different scenarios by the hook type, developer can use the webhook payload to identify what is happening. For example, hook `(before|after)_session_create` will be triggered when creating session, there is `reason` in the payload for developer to know it is `signup` or `login`. If developer wants to block both `signup` and `login`, they only need to implement 1 hook. If they want to block login only, it is clear for them to check the payload reason. The current hooks definition are easy to imagine when the hooks will be triggered, but the developer may need to know what is `session` and `identity`. So I prefer to keep the existing hooks. What do you think?

1. See if you guys have better idea to rename / change the hooks? Some implementation detail: To handle the existing project, we can make a authgear version that support both old and new hook type. We have a `type` in the hook payload, we may need further ask if anyone of them are using that attribute and see how to handle it gracefully. If no one is using that attribute, we can write migration script to migrate all app configs to new hooks. After all apps config have been migrated, then we can update the code to drop the old hooks.

**Comment by louischan-oursky** [comment] 2021-03-11 09:10
My suggestions

1. Remove all `before_*` hooks because they should be replaced by something like Auth0 rules in the future.
2. Remove `user_sync` hook because user cannot be updated now.
3. Remove all `*_session_*` hooks because they are not used.

---

1. Agree `user_create` is more accurate.
2. Agree.
3. One problem raised by Ben was that we use Authgear specific terms `identity` and `session` in the hook name. But I think understanding on the basic concepts (such as User, Identity, Authenticator and Session) are necessary to get job done correctly. Once the concepts are familiar to the developer and they know `after_` means AFTER the whole interaction, the `after_*_*` names are quite obvious.

**Comment by mr9dollars** [comment] 2021-03-11 09:31
@carmenlau @louischan-oursky For point 3, Ben suggested to rename identity to login_id_and_sso, would these make sense to you.

Meeting notes for reference:
```
Rename:
            1. user create > user signup completion
            2. after/before identify create > login id/sso create
```

**Comment by chpapa** [comment] 2021-03-11 12:55
Thanks all! A few thoughts:

1. I don't think `user_create` is more accurate, it is just more ambiguous and not well defined.
   1. Where is the doc for all current hooks? How could I know how many `reason` there are for each webhook?
   2. Do we also have the `reason` for `(before|after)_user_create`? I think it is not really good to have one webhook that could have more than one (and hidden) way to be triggered. This is exactly the situation in the product meeting when I said "we must be able to write the default error message easily". Maybe we better break it down into two webhooks:
      1. `(before|after)_user_signup` called at user signup
      2. `(before|after)_user_create_from_portal` called at user creation from the portal
    1. I think the difference here is, do we want to have more webhooks that are more fine-grind and well defined for each situation, or have fewer webhooks but a `reason` attribute to explain what is the situation? I incline the former as it seems easier to understand from the name. 
    2. A supporting argument is, last time in product meeting, no one specifically said something like "the error message when after_user_create with reason is signup", which we should have known it is ambiguous! How could we assume our users will know?
1. @louischan-oursky said we should remove all `before` hooks as they will be replaced by something like Auth0 rules in the future -- I don't agree with this; Unless we can define what is Auth0 rules now. As we discussed in the last call, we think it is just another webhook but run the JS in VM? However, I don't think we will implement that? So we should just keep it if that's useful (if we can't think of any reason people want the `before` hook, then we can remove it)
1. Agree remove `user_sync`
1. Is it hard to maintain `*_session_*`? I think it is not used now only because we only have a very small sample size? Do they have use cases? (I think yes? e.g. post login hook or post logout hook? But maybe instead of "session" we could give them a better name.
1. "I think understanding on the basic concepts" -- I think the problem is, which we should have discussed it many times, even if it is "possible to understand", we still want to make it as obvious to users as possible. Why it is `after_session_delete` but not `after_user_logout`? Which one is easier to understand?
    1. Similarly... actually is it more easier to understand if we replace `after_identities_create` with `after_new_loginID` and `after_new_SSO`? (Although I'm also not 100% sure about this as the use case is a bit unclear)
1. Another reason why I think we should not use these type of "entities + CRUD" hooks style, is because I think it will be very inconsistent with new webhooks we need to implement. For example, if we want to have a hook for after email was filled in at the sign up page, but before user signup, we might have a hook called `after_signup_filled_email` something like that, which will be in the format of `after_(event_name)`, I think it would just be very inconsistent if we have some hooks are `(before|after)_entity_(created|retrieved|updated|deleted)`, and some are events.

**Comment by carmenlau** [comment] 2021-03-12 01:30
>Where is the doc for all current hooks? How could I know how many reason there are for each webhook?

1.1 Webhook spec: https://github.com/authgear/authgear-server/blob/master/docs/specs/webhook.md

Event list section explain the payload: https://github.com/authgear/authgear-server/blob/master/docs/specs/webhook.md#webhook-event-list

> Do we also have the reason for (before|after)_user_create?

1.2 No, we don't. We only have `reason` for some events, I guess we only added `reason` to hooks that we think it has the use case. e.g. `before_session_create` we can use it in different purpose, we will want to know it is signup / login.
 
> do we want to have more webhooks that are more fine-grind and well defined for each situation, or have fewer webhooks but a reason attribute to explain what is the situation? I incline the former as it seems easier to understand from the name.

1.3 Yes, I think why we don't have conclusion yet, it is because we don't have consensus on this. Actually, both approaches have pros and cons. 

###  fine-grind and well defined for each situation (e.g. `(before|after)_user_signup` + `(before|after)_user_create_from_portal`)

Pros:
- Event type explain everything, developer will not confuse when the event was triggered
- Easier to handle, e.g. writing error message

Cons:
- Developer needs to study and know all the potential hooks that they need to use in some common use case, otherwise they may miss some hooks. e.g. Developer want to implement a hook to notify his server when there is new user in authgear. It looks obvious for him to use `(before|after)_user_signup`, but one day he found authgear won't called his server for some user and found that he missed `(before|after)_user_create_from_portal`. Also, if we go for this way, it should not be `after_new_loginID`, instead we will have something like `after_user_new_loginID` and `after_new_loginID_from_portal`?
- May have some problem in future, when we invent a new way to do the same thing, old apps may miss the new event. e.g. Assume we don't support adding identity in admin portal from day one, developer only implemented `after_user_new_loginID`. After we updated authgear, admin can add login id to user in portal, old app will miss the new event.
- Need to implement/configure multiple hooks for some common use case, e.g. Create a user record in our database when user signed up with authgear

Remarks:
- Need design/implement new event for all new identities (I think actually it is not a cons, but we need to keep remind ourselves we won't miss it when adding new feature, e.g. biometric)

### have fewer webhooks but a reason attribute to explain what is the situation

Pros:
- Developer don't need to implement/configure multiple hooks for some common use case, less chance to miss some events

Cons:
- Developer may confuse when the event being triggered, they need to read the reason in the payload to know the situation.
- More complicated to handle error.
- Difficult to have good event name that can be easily understand by the user

Remarks:
- Need to ensure all events have enough context, e.g. may want to have `reason` in `user_create`

I may missed some points, feel free to add more and help us to make better decision. We need to decide this, and follow the rule to design / change to a new set of hooks. Hope after deciding, we will have clear direction to design the hooks :)

> Is it hard to maintain *_session_*? I think it is not used now only because we only have a very small sample size? Do they have use cases? (I think yes? e.g. post login hook or post logout hook? But maybe instead of "session" we could give them a better name.

4. Let's see what is our decision in 1.3, and see how we change them?

> "I think understanding on the basic concepts" -- I think the problem is, which we should have discussed it many times, even if it is "possible to understand", we still want to make it as obvious to users as possible. Why it is after_session_delete but not after_user_logout? Which one is easier to understand?
Similarly... actually is it more easier to understand if we replace after_identities_create with after_new_loginID and after_new_SSO? (Although I'm also not 100% sure about this as the use case is a bit unclear)

5. Because in the original design,  `session_delete` will be trigged for all session delete case. (logout + revoke). If we strictly follow fine-grind events, this event will split into 3 or more `logout`, `user_revoke_session`, `admin_revoke_user_session`. So for all identities, will become something like `(before|after)_user_new_(loginID|SSO|biometric|...)` and `(before|after)_admin_new_user_(loginID|SSO|biometric|...)`?

> Another reason why I think we should not use these type of "entities + CRUD" hooks style.

6. I think we don't need to stick to "entities + CRUD" hooks style, but still need some format or rule to make events look consistent. For hooks that before and after, it can be something like `(before|after)_(<subject>)_(<verb>)_(<object>)?`, object is optional. (e.g. before_user_signup, before_admin_create_user, before_user_revoke_session, before_admin_revoke_user_session...etc), for event that don't have before and after, just `(<subject>)_(<verb>)_(<object>)?` , (e.g. `user_filled_email`)

**Comment by chpapa** [comment] 2021-03-12 10:39
On fine-grind and well defined for each situation, after reading the comments so far, I'm more inclined to have a fine-grinded one:

1. Agree with the pros for fine-grind hooks.
2. For the Cons of "Developer needs to study and know all the potential hooks that they need to use in some common use case", I think it could be easily solved by having some catch-all hooks as a shortcut. E.g. we can have both `after_user_signup`, `after_user_create_from_portal` and `after_user_create`; The last one which is for all other reasons.
3. For the Cons of "May have some problem in future, when we invent a new way to do the same thing, old apps may miss the new event. ", it could also be a pro. Why we assume when we invent a new way to do the same thing, the users want the old webhook to be called too? And similar to 2, we can have the catch all webhook in those situations.
4. Similarly for the cons of "Need to implement/configure multiple hooks for some common use case"

**** 
However, I'm also thinking, maybe we shouldn't have force ourselves into this binary situation? At the end, we are talking about how can we build an easy-to-use webhooks system for developers.

Stripe is well known for having great API UX for developers, so I take a quick look. (BTW, hey let's always do this, find and try to copy the best practices of others?)

It seems the way they do it is:

* have [ONE webhook](https://stripe.com/docs/api/events), and a list of [event type](https://stripe.com/docs/api/events/types)
* have some common attributes `id`, `api_version`, `request`...
* have a `type`, which seems to follow a certain format, e.g. `charge.dispute.created`, `payment_intend.succeeded`
* have a `data`, which includes all data related to the event type.

Maybe this is better? Since...

1. We can still have a list of event types that explain everything, with a single list the developer won't be confused when the event was triggered.
2. Easier to handle (clear definition, writing good error message)
3. Only implement and configure ONE webhook endpoint, and the developers can easily call multiple functions based on the `type` depends on how he wants the code to be structured
4. Developer will always need to know all the potential events/webhooks anyway, now it is centralized as event type for us.
    1. Maybe we can do a trick to let users do their own "catch all" hooks? e.g. `signup.succeeded.from_portal` and `signup.succeeded.from_user`, so they can choose to just look at the prefix of `signup.succeeded` (is it too tricky?)

However, even if we switch to this way, we still can ask if we want a single event type `signup.succeeded` and with another `reason` field to explain, or as mentioned above, have multiple event type.

Thoughts? @louischan-oursky @carmenlau

**Comment by carmenlau** [comment] 2021-03-15 05:09
Listing out some of the comparison here for discussion in product meeting.

### Stripe

- Events are for notifications only, can not use event to alter / block existing flow.
- One webhook endpoint, all events have same schema. Support list of events type. `data.object` contains the API resource relevant to the event.
- Single event cannot triggered in multiple scenarios. e.g. `custom.created` occurs whenever a new customer is created. Customer can be created via api or through dashboard.

refs:
Event object: https://stripe.com/docs/api/events/object
Event types: https://stripe.com/docs/api/events/types

### Braintree

- Events are for notifications only, can not use event to alter / block existing flow.
- Create create multiple hooks, one hooks can subscribe multiple events.

refs:
Event kinds: https://developers.braintreepayments.com/guides/webhooks/testing-go-live/python#braintree-auth

### Okta
 
- Have 2 kinds of webhook. **Inline hooks** that can pause a flow to add information or make a decision. **Events Hooks** for notifications. https://www.okta.com/blog/2019/08/how-to-use-webhooks-with-okta/
- Single type for one hook entry.
- Inline hooks only have fews supporting type: https://developer.okta.com/docs/concepts/inline-hooks/#currently-supported-types
- Event hooks have a lot of types: https://developer.okta.com/docs/reference/api/event-types/?q=event-hook-eligible. Under each events, there are a list of legacy event types. It looks like they try to combine different events type into one, e.g. see `user.session.start`. And seems the event is triggered in both success and failed case.

I am still checking and updating the above list. But until now, I prefer to separate the hooks that can pause a flow or notification only.

**Comment by carmenlau** [comment] 2021-03-19 08:48
Instead of putting the idea in comment, I wrote the idea into markdown that would be easier for you guys to give comments.
This file will be removed and combined to `webhook.md` after we have consensus.

For reading:
https://github.com/carmenlau/authgear-server/blob/1040-webhooks-spec/docs/specs/webhook_update.md

Can leave comments here:
https://github.com/carmenlau/authgear-server/commit/d4eef43f416a267956f4434d8a621fb1c3b5927c

Discussion questions:
https://github.com/carmenlau/authgear-server/blob/1040-webhooks-spec/docs/specs/webhook_update.md#discussion-questions

**Closed** 2021-04-09 04:01 UTC
