### ISSUE TITLE
Authgear Production on Postmark use Staging Stream ID

### ISSUE THREAD

**Issue by chpapa** [authgear/authgear-server#1288] opened 2021-06-23 07:10 UTC
I just tried the authgear forgot password in production, found the email takes like 5 mins to arrive.

I think it is probably abnormally slow, so I looked into the log, it seems postmark did get the message, so the delay is probably on postmark.

But I found that the production authgear is using the staging stream ID on postmark, that should be fixed.

**Comment by louischan-oursky** [comment] 2021-06-23 07:53
Duplicate of https://github.com/authgear/authgear-server/issues/896

**Comment by fungc-io** [comment] 2021-07-23 10:03
Obsoleted as switeched to sendgrid

**Closed by fungc-io** 2021-07-23 10:03 UTC
