### ISSUE TITLE
Received WhatsApp OTP in Simplified Chinese when locale is zh-HK

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#3718] opened 2024-01-26 10:14 UTC
I set my ui_locales to zh-HK, the AuthUI is showing the correct language.

But the language is wrong in the whatsapp OTP message for verification:

![Image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/60ef6f72-357d-4fcb-80aa-33ffb3fde8a7/97e7f71c-16d8-498f-bfed-c1b2218a7a22?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi82MGVmNmY3Mi0zNTdkLTRmY2ItODBhYS0zM2ZmYjNmZGU4YTcvOTdlN2Y3MWMtMTZkOC00OThmLWJmZWQtYzFiMjIxOGE3YTIyIiwiaWF0IjoxNzA5NzE2NDE2LCJleHAiOjMzMjgwMjc2NDE2fQ.VIdrDE2fLS4z8kx4hxV1IlpKxvz428CjzIQf-BtuzOk)

**Comment by tung2744** [comment] 2024-03-26 07:33
@fungc-io Tested in local, staging and production, but cannot reproduce the problem. Do you have a specific project which can reproduce it?

**Comment by tung2744** [comment] 2024-03-26 08:21
After further testing, if `ui_locales=zh-Hant`, and `zh-HK` `zh-TW` `zh-CN` are enabled for the project, the whatsapp message will be in simplified chinese.

However, if `ui_locales=zh-HK`, the problem doesn't happen.

**Comment by fungc-io** [comment] 2024-03-26 08:23
Thanks @tung2744 for your investigation

I've just tested it again on staging too and seems the problem is gone. Christina reported the same problem before, let me check with her which project was it.

Please put this on hold

**Comment by tung2744** [comment] 2024-03-26 08:25
I think it is the same problem as https://github.com/authgear/authgear-server/issues/3454

For now, if the frontend always use `zh-HK` instead of `zh-Hant`, the locale should be resolved correctly.

**Comment by fungc-io** [comment] 2024-03-26 08:30
🤔 right, it maybe related. Coz they reported the user' system was in "Traditional Chinese" it's a possibility that the device is declaring `zh-hant` in Accept-Language instead of zh-hant-HK/zh-hant-TW/zh-HK/zh-TW…

**Comment by fungc-io** [comment] 2024-03-26 08:33
@tung2744 do we know how to fix #3454?

**Comment by tung2744** [comment] 2024-03-26 08:35
I remembered that is related to the implementation of the golang language package we are using. Which we can only try to find alternative packages.

**Closed** 2024-03-27 18:04 UTC
Labels: bug/minor
