### ISSUE TITLE
Error bar sometimes have no content

### ISSUE THREAD

**Issue by keithtkl** [authgear/authgear-server#576] opened 2020-10-23 06:53 UTC
1. SSO -> enable any one of them and press save without further configuration
![Screenshot 2020-10-23 at 14 51 17](https://user-images.githubusercontent.com/10443251/96965758-47673080-153f-11eb-8d8c-7bf295d375d8.png)

2. Try to save an incorrect configuration on Authentication > Authenticator
![Screenshot 2020-10-23 at 14 52 18](https://user-images.githubusercontent.com/10443251/96965852-7087c100-153f-11eb-997e-bf6a186b9bf0.png)

**Comment by axolotl0212** [comment] 2020-10-23 09:07
This is due to locale key in `ShowUnhandledErrorCause` component is missing

**Comment by axolotl0212** [comment] 2020-10-23 09:09
@nicolaslee2775 sorry, this is already handled when I am handling #561

**Comment by nicolaslee2775** [comment] 2020-10-23 09:33
@axolotl0212 Ok, assigned to you.

**Comment by axolotl0212** [comment] 2020-10-23 09:43
> @axolotl0212 Ok, assigned to you.

Thanks

**Comment by axolotl0212** [comment] 2020-10-23 11:16
> SSO -> enable any one of them and press save without further configuration

empty error message is caused by missing locale key, but this is an unhandled validation error. This is caused by the widget is not extended, so the text field with error is not mounted, so there error is `not handled` (the text field which suppose to consume the error is not mounted). Will follow up in issue #586

**Comment by keithtkl** [comment] 2020-10-28 06:41
@axolotl0212 when no primary authenticator selected, it shows a popup `No usable primary authenticator is enabled` which is OK. but then when switch to Login ID it will show `Failed to update app config` and switch back to authenticator tab again will show `No usable primary authenticator is enabled` again

**Comment by axolotl0212** [comment] 2020-10-28 06:50
> but then when switch to Login ID it will show `Failed to update app config` and switch back to authenticator tab again will show `No usable primary authenticator is enabled` again

The error state is not cleared after switched to different tab. Will split the 2 error states

**Comment by keithtkl** [comment] 2020-10-28 06:57
@axolotl0212 i put a video to better describe the issue, you will see the error dialog shows each time i switch between login id and authenticator
https://youtu.be/Y2fJcdB4yzQ

**Comment by axolotl0212** [comment] 2020-10-28 10:23
This will happen in all screen with tab, if mutation hook is called in screen level instead of inside each tab item. The reason of using hook in screen is to block user interaction (switching tab) while updating. Will handle this with #549 , and reset error state on tab click.

**Closed** 2020-11-02 03:05 UTC
Labels: bug
