### ISSUE TITLE
Web sdk will get CORS error when fetching openid-configuration if not using public origin

### ISSUE THREAD

**Issue by tung2744** [authgear/authgear-server#3458] opened 2023-11-06 05:16 UTC
Even we fixed https://github.com/authgear/authgear-sdk-js/issues/248

If the sdk cannot fetch the openid-configuration after public_origin changed, it is still unusable.
I think we should allow any origin to fetch the open id config.

**Comment by louischan-oursky** [comment] 2023-11-06 05:55
Duplicate of https://github.com/authgear/authgear-server/issues/3205

**Closed** 2023-11-06 06:38 UTC
