### ISSUE TITLE
Increase filtered roles/groups result from 10 to 50

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-server#4379] opened 2024-06-19 14:18 UTC
Show the top 50 result

<img src="https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/2cd60ebb-60af-4f55-bb5f-5e78266adba3/2610d911-d43b-4f49-a1b8-0a53deaad514?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi8yY2Q2MGViYi02MGFmLTRmNTUtYmI1Zi01ZTc4MjY2YWRiYTMvMjYxMGQ5MTEtZDQzYi00ZjQ5LWExYjgtMGE1M2RlYWFkNTE0IiwiaWF0IjoxNzE4ODA2NjgzLCJleHAiOjMzMjg5MzY2NjgzfQ.jmT-cwhR9-9j86VGC96dnr-2nqBalaysA_qOYGR67T8 " alt="image.png" width="678" height="408" />

**Comment by pkong-ds** [comment] 2024-08-09 04:40
More context after investigation

* Seems previously the page size is *intentionally* set to 10 due to performance problem in [Issue #3176](https://github.com/authgear/authgear-server/issues/3176) 
* Then, the performance problem is fixed in [Issue #3233](https://github.com/authgear/authgear-server/issues/3233)

I tried increasing page size, seems no significant load speed difference (locally)

Maybe need to test on staging before/after, see if 50-page-size cause performance issue

**Comment by pkong-ds** [comment] 2024-08-09 05:00
@fungc-io behavior question 🙏 

## Current Behaivor

|  | Size | have pagination? |
| -- | -- | -- |
| page size | 10 | Yes |
| search/filter result size | 10 | No |

## Expected Behavior after this issue

|  | Size | have pagination? |
| -- | -- | -- |
| page size | 10 or 50? (assume 50) | Yes |
| search/filter result size | ***50*** | Yes or No? (assume no) |

**Closed** 2024-08-12 16:02 UTC
