### ISSUE TITLE
[AuthUI] Promote Anonymous User flow missing button to let user choose SMS instead of WhatsApp OTP

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3422] opened 2023-10-25 12:26 UTC
## Environment
- Server: Staging
- App: qa-authflow (Phone + Passwordless)
- Tested user agent:
  - iOS Native demo app
  - Android React Native demo app
- Device: Samsung Galaxy A71 (Android 13), iPhone SE 2 (iOS 16.7)

## Description
When the project is configured with Phone + Passwordless setup, with Anonymous user enabled, if the user triggers "Promote Anonymous User" flow, he/she should fill in phone number and input OTP. But on the WhatsApp OTP screen, the"Send OTP to SMS instead" button is missing in this flow. 

Tried dark mode / light mode / android / ios demo apps.

## Steps to reproduce
1. Setup a project with Phone + Passwordless (with new authflow enabled)
2. Authenticate as anonymous user on demo app
3. Fill in new phone numer, click Sign up
4. See WhatsApp OTP page, but the bottom "Send OTP to SMS instead" button is missing

## Expected result
The button should also exists in promote anonymous user flow as in normal sign up flow, as long as the portal has configured to use WhatsApp or SMS OTP.

## Screenshot

Left: Normal Sign up | Right: Promote Anonymous User

<img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/f02dd2b8-85c7-4b72-900c-cc5448fe5c99" /> <img width=47% src="https://github.com/authgear/authgear-server/assets/12539486/de9e5693-1dda-48a0-b431-6faea7a07a2d" />

Portal:

<img width="894" alt="Screenshot 2023-10-25 at 8 25 15 PM" src="https://github.com/authgear/authgear-server/assets/12539486/49843f51-d793-4662-b615-d73c69a07f76">

**Comment by louischan-oursky** [comment] 2023-10-26 07:13
Duplicate of https://github.com/authgear/authgear-server/issues/3412
Fixed in https://github.com/authgear/authgear-server/pull/3413

**Comment by joyzoursky** [comment] 2023-10-27 09:18
Retest passed

**Closed** 2023-11-07 14:05 UTC
Labels: bug/major, area/authui, reported by qa
