### ISSUE TITLE
[Login] Selected Passwordless still use password login on app

### ISSUE THREAD

**Issue by joyzoursky** [authgear/authgear-server#3327] opened 2023-08-29 08:26 UTC
## Background
- Environment: Staging
- Testing app: refuse-anchor-618, qademoappnative
- Demo apps (native): iOS 1.0(1692936706), android 1.0(1692847081)
- Device: iPhone X (iOS 16.0), pixel 5a (android 13), iPhone SE (iOS 16.4.1 (a))

## Description
Admin user has changed the login method - email to "Passwordless", but after save and configure on the app again, it still asks user to enter password when login.

## Steps to reproduce
1. Select a project on Authgear portal
2. Go to Login Methods > Email
3. Select "Passwordless"
4. Save
5. Configure the application on demo app
6. Click Authenticate to login
7. See that the next step is enter password instead of OTP

## Expected result
Should change to use passwordless login after user changed on portal.

## Screenshot
<img width="1552" alt="Screenshot 2023-08-29 at 4 22 27 PM" src="https://github.com/authgear/authgear-server/assets/12539486/ccacd4a7-eaf9-418a-b13e-79727d36d6c1">

Demo app (after saving on portal and clicked "Configure" button again):

https://github.com/authgear/authgear-server/assets/12539486/293a2e24-66ad-4ad7-9009-75972f5dc862

**Comment by fungc-io** [comment] 2023-08-29 08:29
This is a FAQ, but since asked so frequently, we may want to make some changes.
If the user signed up via password, switching project to passwordless will not affect the old user. It will only affect the new signups.

**Comment by joyzoursky** [comment] 2023-08-29 08:41
changed to ux issue

**Comment by joyzoursky** [comment] 2023-08-29 10:12
After discuss: If have real cases affected by this, we would handle it manually for now (fix old users for client), or see if really need to implement some new handling.

**Comment by chpapa** [comment] 2023-09-01 14:25
Let's close this first as it is sort of by design and either way (automatically update all users to passwordless or not) would be a problem.

And real world scenario could be handled manually

**Comment by chpapa** [comment] 2023-09-01 15:40
2nd thought, actually it's nice to keep a record of issues like these, but for these issues that we won't fix due to design, or no obvious solutions or roadmap, I created a label "idea" to group them.

**Comment by fungc-io** [comment] 2023-11-07 13:50
Fixed in Authflow in https://github.com/authgear/authgear-server/issues/3402

**Closed by fungc-io** 2023-11-07 13:50 UTC
Labels: reported by qa, idea
